-- CropGuard production schema. Apply with `supabase db push` after linking a project.
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_uid uuid unique references auth.users(id) on delete cascade,
  email text not null unique,
  password_hash text,
  role text not null default 'FARMER' check (role in ('FARMER','EXPERT','ADMIN')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.farmer_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  full_name text not null default '', mobile text, state text, district text, village text,
  language text not null default 'English', farm_area numeric(12,3) check (farm_area is null or farm_area >= 0),
  soil_type text, irrigation_type text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.crops (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 80), variety text, sowing_date date, growth_stage text,
  location text, area numeric(12,3) check (area is null or area >= 0), soil_type text, irrigation_type text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.diseases (
  id bigint generated by default as identity primary key, name text not null unique, scientific_name text,
  crops jsonb not null default '[]', symptoms jsonb not null default '[]', causes jsonb not null default '[]',
  favorable_conditions jsonb not null default '[]', prevention jsonb not null default '[]',
  cultural_management jsonb not null default '[]', biological_management jsonb not null default '[]',
  chemical_management jsonb not null default '[]', severity_indicators jsonb not null default '[]',
  kind text not null default 'disease' check (kind='disease'), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.pests (
  id bigint generated by default as identity primary key, name text not null unique, scientific_name text,
  crops jsonb not null default '[]', symptoms jsonb not null default '[]', causes jsonb not null default '[]',
  favorable_conditions jsonb not null default '[]', prevention jsonb not null default '[]',
  cultural_management jsonb not null default '[]', biological_management jsonb not null default '[]',
  chemical_management jsonb not null default '[]', severity_indicators jsonb not null default '[]',
  kind text not null default 'pest' check (kind='pest'), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.crop_scans (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null, crop_id bigint references public.crops(id) on delete set null,
  filename text, kind text not null check (kind in ('disease','pest')), name text not null,
  confidence double precision check (confidence is null or confidence between 0 and 1), severity text,
  risk_level text check (risk_level is null or risk_level in ('LOW','MEDIUM','HIGH')),
  risk_score smallint check (risk_score is null or risk_score between 0 and 100),
  risk_reasons jsonb not null default '[]', weather jsonb not null default '{}', model_name text, model_version text,
  prediction_timestamp timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  crop_scan_id bigint not null references public.crop_scans(id) on delete cascade,
  body text not null, created_at timestamptz not null default now()
);
create table if not exists public.weather_records (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null, location text not null,
  data jsonb not null, created_at timestamptz not null default now()
);
create table if not exists public.risk_assessments (
  id bigint generated by default as identity primary key,
  crop_scan_id bigint not null references public.crop_scans(id) on delete cascade,
  score smallint not null check (score between 0 and 100), level text not null check (level in ('LOW','MEDIUM','HIGH')),
  reasons jsonb not null default '[]', created_at timestamptz not null default now()
);
create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  crop_id bigint references public.crops(id) on delete set null, scan_id bigint references public.crop_scans(id) on delete set null,
  alert_type text not null default 'risk', severity text not null default 'HIGH', title text not null default 'Crop health alert',
  message text not null, is_read smallint not null default 0 check(is_read in (0,1)), dedupe_key text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,dedupe_key)
);
create table if not exists public.expert_reviews (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.crop_scans(id) on delete cascade,
  farmer_id bigint references public.users(id) on delete set null, expert_id bigint references public.users(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','assigned','reviewed','closed')),
  request_note text, response text, confirmed_finding text, confirmed_type text check (confirmed_type is null or confirmed_type in ('disease','pest')),
  severity text, recommendation text, created_at timestamptz not null default now(), reviewed_at timestamptz, updated_at timestamptz not null default now()
);
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key, actor_id bigint references public.users(id) on delete set null,
  action text not null, entity_type text not null, entity_id text, details jsonb not null default '{}', created_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id bigint generated by default as identity primary key, user_id bigint not null references public.users(id) on delete cascade,
  channel text not null default 'in_app' check (channel in ('in_app','email','sms','whatsapp')),
  status text not null default 'pending', title text not null, message text not null,
  created_at timestamptz not null default now(), sent_at timestamptz
);

create index if not exists idx_crops_user_created on public.crops(user_id,created_at desc);
create index if not exists idx_scans_user_created on public.crop_scans(user_id,created_at desc);
create index if not exists idx_scans_crop_created on public.crop_scans(crop_id,created_at desc);
create index if not exists idx_scans_kind_name on public.crop_scans(kind,name);
create index if not exists idx_alerts_user_read_created on public.alerts(user_id,is_read,created_at desc);
create index if not exists idx_reviews_status_created on public.expert_reviews(status,created_at desc);
create index if not exists idx_reviews_expert_status on public.expert_reviews(expert_id,status);
create index if not exists idx_reviews_farmer_created on public.expert_reviews(farmer_id,created_at desc);
create index if not exists idx_weather_location_created on public.weather_records(location,created_at desc);
create index if not exists idx_audit_created on public.audit_log(created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin
  foreach t in array array['users','farmer_profiles','crops','diseases','pests','alerts','expert_reviews'] loop
    execute format('drop trigger if exists touch_updated_at on public.%I',t);
    execute format('create trigger touch_updated_at before update on public.%I for each row execute function public.touch_updated_at()',t);
  end loop;
end $$;
create or replace function public.current_app_role() returns text language sql stable security definer set search_path=public as $$ select role from public.users where auth_uid=auth.uid() limit 1 $$;
create or replace function public.current_app_user_id() returns bigint language sql stable security definer set search_path=public as $$ select id from public.users where auth_uid=auth.uid() limit 1 $$;
create or replace function public.expert_can_access_scan(p_scan_id bigint) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.expert_reviews r
    where r.scan_id=p_scan_id and (r.status in ('pending','assigned') or (r.status='reviewed' and r.expert_id=public.current_app_user_id()))
      and (r.expert_id is null or r.expert_id=public.current_app_user_id()))
$$;
create or replace function public.expert_can_access_crop(p_crop_id bigint) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.expert_reviews r join public.crop_scans s on s.id=r.scan_id
    where s.crop_id=p_crop_id and (r.status in ('pending','assigned') and (r.expert_id is null or r.expert_id=public.current_app_user_id())
      or r.status='reviewed' and r.expert_id=public.current_app_user_id()))
$$;
revoke all on function public.current_app_role() from public;
revoke all on function public.current_app_user_id() from public;
grant execute on function public.current_app_role() to authenticated;
grant execute on function public.current_app_user_id() to authenticated;
revoke all on function public.expert_can_access_scan(bigint) from public;
grant execute on function public.expert_can_access_scan(bigint) to authenticated;
revoke all on function public.expert_can_access_crop(bigint) from public;
grant execute on function public.expert_can_access_crop(bigint) to authenticated;

-- Link legacy SQLite account rows by verified Supabase email. Password hashes are intentionally not imported.
create or replace function public.claim_or_create_user() returns setof public.users
language plpgsql security definer set search_path=public,auth as $$
declare v_auth auth.users%rowtype; v_user public.users%rowtype; v_name text;
begin
  select * into v_auth from auth.users where id=auth.uid();
  if not found or v_auth.email_confirmed_at is null then raise exception 'verified auth session required'; end if;
  v_name := coalesce(v_auth.raw_user_meta_data->>'full_name','');
  update public.users set auth_uid=v_auth.id,email=lower(v_auth.email),updated_at=now()
    where lower(email)=lower(v_auth.email) and auth_uid is null returning * into v_user;
  if not found then
    insert into public.users(auth_uid,email,role) values(v_auth.id,lower(v_auth.email),'FARMER')
      on conflict(auth_uid) do update set email=excluded.email returning * into v_user;
  end if;
  insert into public.farmer_profiles(user_id,full_name) values(v_user.id,v_name)
    on conflict(user_id) do update set full_name=case when farmer_profiles.full_name='' then excluded.full_name else farmer_profiles.full_name end;
  return next v_user;
end $$;
revoke all on function public.claim_or_create_user() from public;
grant execute on function public.claim_or_create_user() to authenticated;
create or replace function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public,auth as $$
declare v_user public.users%rowtype;
begin
  update public.users set auth_uid=new.id,email=lower(new.email),updated_at=now()
    where lower(email)=lower(new.email) and auth_uid is null returning * into v_user;
  if not found then
    insert into public.users(auth_uid,email,role) values(new.id,lower(new.email),'FARMER')
      on conflict(auth_uid) do update set email=excluded.email returning * into v_user;
  end if;
  insert into public.farmer_profiles(user_id,full_name) values(v_user.id,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict(user_id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();

alter table public.users enable row level security;
alter table public.farmer_profiles enable row level security;
alter table public.crops enable row level security;
alter table public.crop_scans enable row level security;
alter table public.diseases enable row level security;
alter table public.pests enable row level security;
alter table public.recommendations enable row level security;
alter table public.weather_records enable row level security;
alter table public.risk_assessments enable row level security;
alter table public.alerts enable row level security;
alter table public.expert_reviews enable row level security;
alter table public.audit_log enable row level security;
alter table public.notifications enable row level security;

grant select on public.users to authenticated;
grant select,insert,update,delete on public.farmer_profiles,public.crops,public.crop_scans,public.recommendations,public.weather_records,public.risk_assessments,public.alerts,public.expert_reviews to authenticated;
grant select on public.diseases,public.pests to anon,authenticated;
grant insert,update,delete on public.diseases,public.pests to authenticated;
grant select,insert on public.audit_log to authenticated;
grant select,insert,update on public.notifications to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create policy users_self_select on public.users for select to authenticated using(auth_uid=auth.uid() or public.current_app_role()='ADMIN');
create policy profiles_owner_all on public.farmer_profiles for all to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN') with check(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN');
create policy crops_owner_all on public.crops for all to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN') with check(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN');
create policy scans_owner_select on public.crop_scans for select to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN' or (public.current_app_role()='EXPERT' and (public.expert_can_access_scan(id) or public.expert_can_access_crop(crop_id))));
create policy scans_owner_insert on public.crop_scans for insert to authenticated with check(user_id=public.current_app_user_id());
create policy scans_owner_update on public.crop_scans for update to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN') with check(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN');
create policy scans_owner_delete on public.crop_scans for delete to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN');
create policy diseases_public_read on public.diseases for select to anon,authenticated using(true);
create policy diseases_admin_write on public.diseases for all to authenticated using(public.current_app_role()='ADMIN') with check(public.current_app_role()='ADMIN');
create policy pests_public_read on public.pests for select to anon,authenticated using(true);
create policy pests_admin_write on public.pests for all to authenticated using(public.current_app_role()='ADMIN') with check(public.current_app_role()='ADMIN');
create policy recommendations_owner on public.recommendations for all to authenticated using(exists(select 1 from public.crop_scans s where s.id=crop_scan_id and (s.user_id=public.current_app_user_id() or public.current_app_role()='ADMIN'))) with check(exists(select 1 from public.crop_scans s where s.id=crop_scan_id and (s.user_id=public.current_app_user_id() or public.current_app_role()='ADMIN')));
create policy weather_owner on public.weather_records for all to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN') with check(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN');
create policy risks_owner on public.risk_assessments for all to authenticated using(exists(select 1 from public.crop_scans s where s.id=crop_scan_id and (s.user_id=public.current_app_user_id() or public.current_app_role()='ADMIN'))) with check(exists(select 1 from public.crop_scans s where s.id=crop_scan_id and (s.user_id=public.current_app_user_id() or public.current_app_role()='ADMIN')));
create policy alerts_owner on public.alerts for all to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN') with check(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN');
create policy reviews_read on public.expert_reviews for select to authenticated using(farmer_id=public.current_app_user_id() or public.current_app_role()='ADMIN' or (public.current_app_role()='EXPERT' and ((status in ('pending','assigned') and (expert_id is null or expert_id=public.current_app_user_id())) or (status='reviewed' and expert_id=public.current_app_user_id()))));
create policy reviews_farmer_insert on public.expert_reviews for insert to authenticated with check(farmer_id=public.current_app_user_id() and expert_id is null and status='pending' and response is null and reviewed_at is null and exists(select 1 from public.crop_scans s where s.id=scan_id and s.user_id=public.current_app_user_id()));
create policy reviews_expert_update on public.expert_reviews for update to authenticated using(public.current_app_role()='ADMIN' or (public.current_app_role()='EXPERT' and status in ('pending','assigned') and (expert_id is null or expert_id=public.current_app_user_id()))) with check(public.current_app_role()='ADMIN' or (public.current_app_role()='EXPERT' and expert_id=public.current_app_user_id()));
create policy reviews_admin_delete on public.expert_reviews for delete to authenticated using(public.current_app_role()='ADMIN');
create policy audit_owner_insert on public.audit_log for insert to authenticated with check(actor_id=public.current_app_user_id());
create policy audit_admin_read on public.audit_log for select to authenticated using(public.current_app_role()='ADMIN');
create policy notifications_owner on public.notifications for all to authenticated using(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN') with check(user_id=public.current_app_user_id() or public.current_app_role()='ADMIN');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('crop-images','crop-images',false,5242880,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;
create policy crop_images_owner_read on storage.objects for select to authenticated using(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy crop_images_owner_insert on storage.objects for insert to authenticated with check(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy crop_images_owner_update on storage.objects for update to authenticated using(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy crop_images_owner_delete on storage.objects for delete to authenticated using(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);
